### ISSUE TITLE
Clair is not up and running restarts in infinite loop

### ISSUE THREAD

**Issue by poojatr** [x-cellent/blog-clair-test#1]
I am using docker windows
I found your tutorial, (https://www.x-cellent.com/blog/build-your-own-clair-registry/)
 followed all the steps, but when docker-compose up -d is done..

Creating newclair_registry_1 ... done
Creating clair_postgres      ... done
Creating clair_clair         ... done

but when docker ps is given , the output is 
 STATUS                          PORTS               NAMES
d08da3e0682e        quay.io/coreos/clair:latest   "/clair -config /con…"   40 minutes ago      Restarting (1) 25 seconds ago                       clair_clair
c794eb8d1376        postgres:latest               "docker-entrypoint.s…"   40 minutes ago      Up 40 minutes                                       clair_postgres
f463f9b80ddd        registry:latest               "/entrypoint.sh /etc…"   40 minutes ago      Up 40 minutes                                       newclair_registry_1

Clair is not up and running? , am i doing anything wrong?

Sorry for the silly question , i am new to dockers and clair .. but am trying to set up clair since a week and not able to, Will appreciate your assistance, Thank you

**Comment by poojatr** [comment]
I even tried on centos-7 machine to install clair which has the umask of 0022

but i get the error **"error":"open /config/config.yaml: permission denied"**

i have tried

* **sudo** docker run --net=host -d -p 6060-6061:6060-6061 -v $PWD/clair_config:/config quay.io/coreos/clair-git:latest -config=/config/config.yaml
* ./common/config/clair/config.yaml is this file and the one created under clair_config directory config.yaml different ? (  I am following the docker method of installing https://github.com/coreos/clair/blob/master/Documentation/running-clair.md )

do we need git,rpm and xz as runtime dependency?

Sorry, if it sounds like a stupid question, but am trying to get clair up and running since a week but running into same isuue..

It will be a great help if this doubt can be solved.

This may be a duplicate of [clair container can not get up, the log shows: open / configure / config.yaml: permission denied " #3478](https://github.com/goharbor/harbor/issues/3478)

**Comment by Pilzington** [comment]
Hey @poojatr 

The method from the tutorial will only work on Linux. I used Ubuntu to try it out.  
But you can look at the error message of the containers with:
`docker logs [container-name]`
  
Have you tried my tutorial also on centos-7? I never tried to install Clair like that, but I know that you only need git, rpm, and xz if you build it directly from the source without Docker. I prefer docker-compose because you need a database for Clair. 
  
This [resource](https://www.katacoda.com/courses/docker-security/image-scanning-with-clair) helped me a lot getting acquainted with Clair.

**Comment by poojatr** [comment]
@Pilzington thank you so much, i got it working it was a problem with mounting 

In case of centos 

docker run --net=host -d -p 6060-6061:6060-6061 -v $PWD/cl
air_config:/config**:Z** quay.io/coreos/clair-git:latest -config=/config/config.yaml


[`Because SELinux interrupts attaching volumes `](https://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/)

Thank you, i appreciate your response
